### PR TITLE
chore: update container version to v48

### PR DESCRIPTION
**Pull request by ShadowCurse**
### Summary of the PR

Update container version to v48

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [ ] All commits in this PR have Signed-Off-By trailers (with
  `git commit -s`), and the commit message has max 60 characters for the
  summary and max 75 characters for each description line.
- [ ] All added/changed functionality has a corresponding unit/integration
  test.
- [ ] All added/changed public-facing functionality has entries in the "Upcoming 
  Release" section of CHANGELOG.md (if no such section exists, please create one).
- [ ] Any newly added `unsafe` code is properly documented.

### CODE REVIEW

**Comment by TimePrinciple** [comment]
Shouldn't the version be of `v48` 😮

**Review by roypat — DISMISSED** [review]

**Comment by roypat** [comment]
> Shouldn't the version be of `v48` in the title 😮

yes haha

**Comment by stefano-garzarella** [comment]
> Shouldn't the version be of `v48` in the title 😮

Yep, @ShadowCurse please update it in the commit title too.

**Review by roypat — APPROVED** [review]

**Review by stefano-garzarella — APPROVED** [review]
Please next time put something in the commit description, like new features/fix or link to the PRs included in the new container version.
See cdb4a2d5cd207846b51407c96a01a175efc0b274 as an example.

**Pull request merged**
